### ISSUE TITLE
After reboot, the system reverts back to rancher/k3os

### ISSUE THREAD

**Issue by vdboor** [mazzy89/k3os#6]
I've upgraded the system by changing the channel, but it reverted back to rancher/k3os alter upgrading or rebooting.

**Steps taken:**
```
kubectl edit plan -n k3os-system k3os-latest
# change channel to: https://github.com/mazzy89/k3os/releases/latest
```

My node still used the "upgrade" instead of "latest" value, so fixed that too:

```
kubectl label node --overwrite k3os-1234 k3os.io/upgrade=latest
```

**Result:**
After the upgrade, the plan's channel is reverted back to the rancher/k3os repository.

Upon reboot, the`/k3os/system/config.yaml` is reapplied, and this likely also restores the plan channel.

My workaround for now is manually fixing the plan after an upgrade.

**Other observations:**

* I noticed that the upgrade plan's `spec.upgrade.image` still uses the `rancher/k3os` docker image.
* The plan file in this repo still points to old rancher/k3os github repo
* `/var/lib/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml` points to the old repo
* `/usr/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml` points to the old repo

**Comment by mazzy89** [comment]
I’m planning to wire a new release and patch this.

**Comment by mazzy89** [comment]
WIth the new this issue won't happen again. The manifest is now up to date and point to this repo.
